import { getReportDetails } from "@/app/reports/actions";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import PrintTrigger from "./print-trigger";

export const dynamic = 'force-dynamic';

export default async function ReportPrintPage({ params }: { params: { id: string } }) {
  const report = await getReportDetails(params.id);

  if (!report) {
    return (
      <div className="p-10 text-center font-sans">
        <h1 className="text-2xl font-bold">Report Not Found</h1>
        <p>The report you are looking for with ID "{params.id}" does not exist.</p>
      </div>
    );
  }

  const statusVariant = {
    'Finalized': 'default',
    'Draft': 'secondary',
  } as const;

  return (
    <>
      <div className="max-w-4xl mx-auto p-4 font-sans text-gray-800">
        <header className="flex justify-between items-start mb-8">
          <div>
            <h1 className="text-4xl font-bold text-gray-900">Audit Report</h1>
            <p className="text-gray-600">{report.title}</p>
          </div>
          <div className="flex items-center gap-2 text-xl font-bold tracking-tight text-gray-900">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="h-7 w-7 text-primary"
            >
              <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
              <polyline points="14 2 14 8 20 8" />
              <path d="m10 10.5 4 4" />
              <path d="m14 10.5-4 4" />
            </svg>
            <span>X-Audit</span>
          </div>
        </header>

        <main>
          <div className="grid grid-cols-3 gap-4 mb-8 text-sm p-4 bg-gray-50 rounded-lg border">
            <div>
              <p className="font-semibold text-gray-500">Report ID</p>
              <p>{report.id}</p>
            </div>
            <div>
              <p className="font-semibold text-gray-500">Date Generated</p>
              <p>{report.date}</p>
            </div>
            <div>
              <p className="font-semibold text-gray-500">Generated By</p>
              <p>{report.generated_by.name}</p>
            </div>
            <div>
              <p className="font-semibold text-gray-500">Audit ID</p>
              <p>{report.audit_id}</p>
            </div>
            <div>
              <p className="font-semibold text-gray-500">Status</p>
              <Badge variant={statusVariant[report.status]}>{report.status}</Badge>
            </div>
          </div>
          
          <Separator className="my-8" />
          
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-3">Executive Summary</h2>
            <p className="text-gray-700 leading-relaxed">{report.summary}</p>
          </section>

          {report.compliance_score !== null && (
            <>
              <Separator className="my-8" />
              <section className="mb-8">
                <h2 className="text-2xl font-semibold mb-3">Compliance Status</h2>
                <div className="p-4 bg-primary/10 rounded-lg">
                  <p className="font-bold text-3xl text-primary">{report.compliance_score}% Compliant</p>
                  <p className="text-gray-600 mt-1">{report.compliance_details}</p>
                </div>
              </section>
            </>
          )}

          {report.findings && report.findings.length > 0 && (
            <>
              <Separator className="my-8" />
              <section>
                <h2 className="text-2xl font-semibold mb-4">Key Findings & Recommendations</h2>
                <div className="space-y-6">
                  {report.findings.map((finding, index) => (
                    <div key={finding.id} className="p-4 border rounded-lg bg-gray-50/50 break-inside-avoid">
                      <h3 className="font-bold text-lg">{index + 1}. {finding.title}</h3>
                      <p className="text-gray-600 mt-2 pl-5">
                        <span className="font-semibold">Recommendation:</span> {finding.recommendation}
                      </p>
                    </div>
                  ))}
                </div>
              </section>
            </>
          )}
        </main>

        <footer className="mt-12 text-center text-xs text-gray-500">
          <p>This is a computer-generated document from X-Audit.</p>
        </footer>
      </div>
      <PrintTrigger />
    </>
  );
}
